export { default as Navbar } from './Navbar/Navbar';
export { default as Hero } from './Hero/Hero';
export { default as Marquee } from './Marquee/Marquee';
export { default as Features } from './Features/Features';
export { default as JudgingSystem } from './JudgingSystem/JudgingSystem';
export { default as Gallery } from './Gallery/Gallery';
export { default as About } from './About/About';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';
