import React, { useEffect, useRef, useState } from "react";
import "./Gallery.css";

const VISIBLE_COUNT = 6;
const SHUFFLE_INTERVAL = 3500; // ms between each shuffle tick
const FLIP_OUT_DURATION = 400; // ms — must match the flip-out transition in CSS
const FLIP_IN_DELAY = 100; // ms — small gap so the browser registers the new state before transitioning back in

// Fisher-Yates shuffle, returns a new shuffled copy
function shuffleArray(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

export default function Gallery() {
  const inputRef = useRef();
  const [uploaded, setUploaded] = useState([]);
  const [pool, setPool] = useState([]);
  const [indices, setIndices] = useState([]);
  const [flipping, setFlipping] = useState(Array(VISIBLE_COUNT).fill(false));
  const [loadError, setLoadError] = useState(null);

  const bagRef = useRef([]);
  const retiredRef = useRef([]);
  const lastSlotRef = useRef(null);

  // Track every pending timer/animation-frame so we can cancel ALL of
  // them on cleanup — not just the outer interval. Without this, a
  // shuffle that's mid-flight when the effect re-runs (Strict Mode,
  // HMR, etc.) leaves an orphaned timer that can set a slot's
  // "flipping" state to true and never back to false, permanently
  // hiding that card. Over many shuffles this compounds until every
  // card is invisible.
  const pendingTimersRef = useRef([]);

  const clearAllPendingTimers = () => {
    pendingTimersRef.current.forEach((id) => {
      clearTimeout(id.timeout);
      id.rafs.forEach((raf) => cancelAnimationFrame(raf));
    });
    pendingTimersRef.current = [];
  };

  // Load manifest.json generated by the rename script
  useEffect(() => {
    fetch("/logo/Gallery/manifest.json")
      .then((res) => {
        if (!res.ok) throw new Error(`manifest.json returned ${res.status}`);
        return res.json();
      })
      .then((data) => {
        const items = data.map((item) => ({
          type: item.type,
          url: `/logo/Gallery/${item.file}`,
          label: item.label || item.file,
        }));
        setPool(items);

        const visibleCount = Math.min(VISIBLE_COUNT, items.length);
        const initial = Array.from({ length: visibleCount }, (_, i) => i);
        setIndices(initial);
        setFlipping(Array(visibleCount).fill(false));

        const remaining = items
          .map((_, i) => i)
          .filter((i) => i >= visibleCount);
        bagRef.current = shuffleArray(remaining);
        retiredRef.current = [];
      })
      .catch((err) => {
        console.error("Failed to load gallery manifest:", err);
        setLoadError(err.message);
      });
  }, []);

  useEffect(() => {
    if (pool.length <= VISIBLE_COUNT) return; // nothing to rotate through

    const timer = setInterval(() => {
      if (bagRef.current.length === 0) {
        bagRef.current = shuffleArray(retiredRef.current);
        retiredRef.current = [];
      }
      if (bagRef.current.length === 0) return;

      let slot;
      do {
        slot = Math.floor(Math.random() * VISIBLE_COUNT);
      } while (slot === lastSlotRef.current && VISIBLE_COUNT > 1);
      lastSlotRef.current = slot;

      const drawPos = Math.floor(Math.random() * bagRef.current.length);
      const nextIdx = bagRef.current[drawPos];
      bagRef.current = bagRef.current.filter((_, i) => i !== drawPos);

      setFlipping((prev) => {
        const next = [...prev];
        next[slot] = true;
        return next;
      });

      const timerEntry = { timeout: null, rafs: [] };
      pendingTimersRef.current.push(timerEntry);

      timerEntry.timeout = setTimeout(() => {
        setIndices((prev) => {
          retiredRef.current.push(prev[slot]);
          const next = [...prev];
          next[slot] = nextIdx;
          return next;
        });

        const raf1 = requestAnimationFrame(() => {
          const raf2 = requestAnimationFrame(() => {
            setFlipping((prev) => {
              const next = [...prev];
              next[slot] = false;
              return next;
            });
            // This timer entry is done — drop it from the pending list.
            pendingTimersRef.current = pendingTimersRef.current.filter(
              (t) => t !== timerEntry,
            );
          });
          timerEntry.rafs.push(raf2);
        });
        timerEntry.rafs.push(raf1);
      }, FLIP_OUT_DURATION + FLIP_IN_DELAY);
    }, SHUFFLE_INTERVAL);

    return () => {
      clearInterval(timer);
      clearAllPendingTimers();
      // Safety net: if anything was mid-flip when we tore down, make
      // sure no card is left permanently stuck invisible.
      setFlipping(Array(VISIBLE_COUNT).fill(false));
    };
  }, [pool]);

  const handleFiles = (e) => {
    const files = Array.from(e.target.files);
    const urls = files.map((f) => ({
      url: URL.createObjectURL(f),
      name: f.name,
      type: f.type,
    }));
    setUploaded((prev) => [...prev, ...urls]);
  };

  return (
    <section className="gallery" id="gallery">
      <div className="gallery__header">
        <div className="section-label gallery__label fade-up">
          Visual Archive
        </div>
        <h2
          className="section-title fade-up stagger-1"
          style={{ color: "var(--white)" }}
        >
          Moments in <em>motion</em>
        </h2>
      </div>

      {pool.length === 0 && (
        <p style={{ color: "rgba(255,255,255,0.5)", fontSize: "0.85rem" }}>
          {loadError
            ? `Couldn't load gallery images (${loadError}). Check that public/logo/Gallery/manifest.json exists.`
            : "Loading gallery…"}
        </p>
      )}

      <div className="gallery__grid">
        {indices.map((imgIdx, slot) => {
          const item = pool[imgIdx];

          return (
            <div
              key={slot}
              className={`gallery__card gallery__card--${slot} ${
                flipping[slot] ? "gallery__card--flipping" : ""
              }`}
            >
              <img src={item.url} className="gallery__media" alt={item.label} />

              <div className="gallery__card-label">{item.label}</div>
            </div>
          );
        })}

        {/* Uploaded previews */}
        {uploaded.map((f, i) => (
          <div
            className="gallery__card gallery__card--uploaded fade-up"
            key={`up-${i}`}
          >
            {f.type.startsWith("video") ? (
              <video src={f.url} className="gallery__media" muted />
            ) : (
              <img src={f.url} alt={f.name} className="gallery__media" />
            )}
            <div className="gallery__card-label">{f.name}</div>
          </div>
        ))}
      </div>
    </section>
  );
}
